custom:
  text_current: '{current} von {total}'
  text_previous: '« Zurück'
  text_next: 'Weiter »'
  text_close: Schließen
  maxwidth: 98%
  maxheight: 98%
  initialwidth: '300'
  initialheight: '250'
  slideshow:
    text_start: 'Slideshow starten'
    text_stop: 'Slideshow anhalten'
