<?php


use Drupal\Core\Routing\RouteMatchInterface;


function custom_owlcarousel_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  //$build['#title'] = t('New title of the block');
  //echo "<pre>";
  //print_r($block);
  //echo "</pre>";
  if ($block
      ->label() === 'slideshow') {
    exit();
  }
    //print_r($build['#cache']['contexts'][]);
}

//function hook_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
//
//  // Add the 'user' cache context to some blocks.

//  }
//}


/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter.
 */
/*function custom_owlcarousel_block_view_views_block__slideshow_block_1_alter(array &$build, $block) {
  exit();
  //echo "testxxx";

//  if ($variables['view']->storage->id() == 'slideshow') {
//    echo "testxxx";
//    $variables['#attached']['library'][] = 'custom_owlcarousel/custom_owlcarousel';
//  }
}*/

/**
 * Implements hook_help().
 */
function custom_owlcarousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_owlcarousel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('About Custom Owl-Carousel') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
//function custom_owlcarousel_theme($existing, $type, $theme, $path) {
//return [
//    'custom_owlcarousel_example_first' => [
//      'variables' => [],
//    ],
//  ];
//}
/**
 * Implements template_preprocess_HOOK().
 * Обработчик переменных для первого примера.
 */
//function template_preprocess_custom_owlcarousel_example_first(&$variables) {
//  $date_formatter = \Drupal::service('date.formatter');
//  $variables['date'] = $date_formatter->format(time());
//
//  if ($variables['view']->storage->id() == 'slideshow') {
//    echo "testxxx";
//    $variables['#attached']['library'][] = 'custom_owlcarousel/custom_owlcarousel';
//  }
//}
